Potenciômetro Motorizado - ADC/ PWM - biblioteca PID ARM
Insper/SAME70-examples pull request #48
Opened 2022-12-06 14:36 UTC by TiagoSeixas2103

22b-av-assincrona
Tiago Vitorino Seixas

2022-12-07 11:45 UTC, rafaelcorsi requested changes
O código de forma geral tá ok, mas precisa melhorar algumas coisas de C e formatação visual (linhas em branco, sem padrão de código) sugiro você passar por algum autoformat

2022-12-07 19:39 UTC, TiagoSeixas2103 commented on Atuadores/Potenciometro_Motorizado-PWM-PID/firmware/src/main.c
> +		}
feito

2022-12-07 19:39 UTC, TiagoSeixas2103 commented on Atuadores/Potenciometro_Motorizado-PWM-PID/firmware/src/main.c
> +		}
tirei

2022-12-07 19:40 UTC, TiagoSeixas2103 commented on Atuadores/Potenciometro_Motorizado-PWM-PID/firmware/src/main.c
> +
tirei

2022-12-07 19:40 UTC, TiagoSeixas2103 commented on Atuadores/Potenciometro_Motorizado-PWM-PID/firmware/src/main.c
> +	char *valores_potenciometro[]={&nome1, &nome2, &nome3};
fiz

2022-12-07 19:40 UTC, TiagoSeixas2103 commented on Atuadores/Potenciometro_Motorizado-PWM-PID/firmware/src/main.c
> +			}
troquei por else if

2022-12-10 12:51 UTC, rafaelcorsi requested changes
Precisa melhorar o README:

- Colocar diagrama (tipo os da prova) para explicar o firmware
- Você não fala nada da biblioteca CMSIS de PID 
-  Não tem nada do tune do PID
-  Cadê os gráficos (osciloscópio) que eu pedi? Com as explicações
- Remover os trechos de código duplicado, o código que realmente precisava vc não explica que é a parte de usar o CMSIS ...

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +![alt text](https://github.com/TiagoSeixas2103/22b-emb-af-TiagoSeixas2103/blob/main/Ptenciometro.jpeg)
isso aqui não funcionou

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +
Colocar o seu nome e email:

- Ano: 22b
- Aluno: Thiago...
- email:

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +Muda a resistência do potênciometro usando um motor para chegar ao valor de resistência determinado ao apertar o botão da placa OLED, e por meio de PWM (Pulse Width Modulation) normalizada por um con
o objetivo não é mudar a resistência, mas controlar o motor dado uma posição.. a resistência é consequência.

melhorar o texto do que o projeto faz.

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +![alt text](https://github.com/TiagoSeixas2103/22b-emb-af-TiagoSeixas2103/blob/main/Ptenciometro.jpeg)
não tem nenhuma imagem

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +- Conectar placa OLED no EXT1 da placa Atmel
não gostei... vai ficar melhor com uma tabela!

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +
Colcar lista de componentes e periféricos usados no exemplo

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +Se utiliza do valor atual do potenciômetro e o valor solicitado ao pressionar um dos botões da placa OLED para saber qual o erro do PID (diferença entre valor atual e valor desejado). Caso o erro sej
o PID não é um erro, mas sim um controlador... melhorar

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +Foram utilizadas quatro funções de callback e um handler no handout.
handout?

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +void RTT_Handler(void) {
não seria melhor usar o TC?

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +```
pode tirar

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +```
tirar.. não tem sentido colocar muito código assim, só se for explicar e colocar trechos 
```suggestion

```

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +```
```suggestion

```
Explicar de forma mais ampla, o código aqui não agrega... se quiser pode fazer um link com o código real

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +```
```suggestion
```

2022-12-10 12:51 UTC, rafaelcorsi commented on Atuadores/Potenciometro_Motorizado-PWM-PID/README.md
> +```
```suggestion


```

2022-12-14 14:16 UTC, merged